backend:
  name: github
  repo: awfulxo/portfolio
  branch: main
  base_url: https://decap-cms-oauth-mauve.vercel.app

locale: "ru"
site_url: "https://awfulxo.github.io/portfolio/"

media_folder: "images"
public_folder: "images"

collections:
  - name: "concept"
    label: "Концепт (фото)"
    files:
      - name: "concept"
        label: "Галерея концепта"
        file: "data/concept.json"
        fields:
          - { label: "Фото", name: items, widget: list, field: { label: "Файл", name: src, widget: image } }

  - name: "animation"
    label: "Анимация (видео)"
    files:
      - name: "animation"
        label: "Галерея видео"
        file: "data/animation.json"
        fields:
          - { label: "Видео", name: items, widget: list, field: { label: "Ссылка на YouTube (или файл)", name: src, widget: string, hint: "Вставь ссылку на YouTube-видео" } }
