backend:
  name: github
  repo: awfulxo/portfolio
  branch: main
  base_url: https://decap-cms-oauth-mauve.vercel.app

locale: "ru"
site_url: "https://awfulxo.github.io/portfolio/"

media_folder: "images"
public_folder: "images"

collections:
  - name: "concept"
    label: "Концепт (фото)"
    files:
      - name: "concept"
        label: "Галерея концепта"
        file: "data/concept.json"
        fields:
          - label: "Фото"
            name: items
            widget: list
            summary: "{{src}}"
            fields:
              - { label: "Файл", name: src, widget: image }
              - { label: "Ширина (px, необязательно)", name: size, widget: number, required: false, value_type: int, hint: "Оставь пустым для размера по умолчанию" }

  - name: "animation"
    label: "Анимация (видео)"
    files:
      - name: "animation"
        label: "Галерея видео"
        file: "data/animation.json"
        fields:
          - label: "Видео"
            name: items
            widget: list
            summary: "{{src}}"
            fields:
              - { label: "Ссылка на YouTube (или файл)", name: src, widget: string, hint: "Вставь ссылку на YouTube-видео" }
              - { label: "Ширина (px, необязательно)", name: size, widget: number, required: false, value_type: int, hint: "Оставь пустым для размера по умолчанию" }
