backend:
  name: github
  repo: RomanDenis/portfolio
  branch: main
  base_url: https://decap-cms-oauth-mauve.vercel.app

media_folder: "images"
public_folder: "images"

collections:
  - name: "concept"
    label: "Концепт (фото)"
    files:
      - name: "concept"
        label: "Галерея концепта"
        file: "data/concept.json"
        fields:
          - { label: "Фото", name: items, widget: list, field: { label: "Файл", name: src, widget: image } }

  - name: "illustration"
    label: "Иллюстрации (фото)"
    files:
      - name: "illustration"
        label: "Галерея иллюстраций"
        file: "data/illustration.json"
        fields:
          - { label: "Фото", name: items, widget: list, field: { label: "Файл", name: src, widget: image } }

  - name: "animation"
    label: "Анимация (видео)"
    files:
      - name: "animation"
        label: "Галерея видео"
        file: "data/animation.json"
        fields:
          - { label: "Видео", name: items, widget: list, field: { label: "Файл", name: src, widget: file, media_folder: "/videos", public_folder: "/videos" } }
