name: Build assets.json

on:
  push:
    branches:
      - main  # или master, если у тебя ветка называется master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Генерируем assets.json
      - name: Generate assets.json
        run: node generate-assets.js

      # 4. Пушим изменения обратно в репо
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
